// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuv0muPqCDJdIQrfoHnjjNqiTYsZhmYiw',
    appId: '1:430371129269:web:c5c7e1b104bb40a5a7fbfc',
    messagingSenderId: '430371129269',
    projectId: 'retrouvetout-6b210',
    authDomain: 'retrouvetout-6b210.firebaseapp.com',
    storageBucket: 'retrouvetout-6b210.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgFpHzWKHhf07I3LvsXxqlV17HYcmdqcw',
    appId: '1:430371129269:android:204d7d99fa83ac4ba7fbfc',
    messagingSenderId: '430371129269',
    projectId: 'retrouvetout-6b210',
    storageBucket: 'retrouvetout-6b210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtUXeHFJNDTdKG7WOs0RhtchnaRPO85jU',
    appId: '1:430371129269:ios:33f9c66637dad735a7fbfc',
    messagingSenderId: '430371129269',
    projectId: 'retrouvetout-6b210',
    storageBucket: 'retrouvetout-6b210.firebasestorage.app',
    iosBundleId: 'com.example.retrouveTout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtUXeHFJNDTdKG7WOs0RhtchnaRPO85jU',
    appId: '1:430371129269:ios:33f9c66637dad735a7fbfc',
    messagingSenderId: '430371129269',
    projectId: 'retrouvetout-6b210',
    storageBucket: 'retrouvetout-6b210.firebasestorage.app',
    iosBundleId: 'com.example.retrouveTout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuv0muPqCDJdIQrfoHnjjNqiTYsZhmYiw',
    appId: '1:430371129269:web:9c8dbff3c0a9c1aaa7fbfc',
    messagingSenderId: '430371129269',
    projectId: 'retrouvetout-6b210',
    authDomain: 'retrouvetout-6b210.firebaseapp.com',
    storageBucket: 'retrouvetout-6b210.firebasestorage.app',
  );

}