// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTUJNMdaDOWdlj-LDMSkS7Lm5a2fRG1EA',
    appId: '1:930156239352:web:68457e4a7491b176861e0d',
    messagingSenderId: '930156239352',
    projectId: 'retrouvetout-c92ba',
    authDomain: 'retrouvetout-c92ba.firebaseapp.com',
    storageBucket: 'retrouvetout-c92ba.firebasestorage.app',
    measurementId: 'G-G55LN7FVKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUozxfn7G4M6fTYk8OcsLAB9cKdtcVc28',
    appId: '1:930156239352:android:be269fef608afbf7861e0d',
    messagingSenderId: '930156239352',
    projectId: 'retrouvetout-c92ba',
    storageBucket: 'retrouvetout-c92ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBitkIuFs9I7RzjDdTRczF6f-nbGQr5g',
    appId: '1:930156239352:ios:48e4e2001e1170c2861e0d',
    messagingSenderId: '930156239352',
    projectId: 'retrouvetout-c92ba',
    storageBucket: 'retrouvetout-c92ba.firebasestorage.app',
    iosBundleId: 'com.example.retrouveTout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBitkIuFs9I7RzjDdTRczF6f-nbGQr5g',
    appId: '1:930156239352:ios:48e4e2001e1170c2861e0d',
    messagingSenderId: '930156239352',
    projectId: 'retrouvetout-c92ba',
    storageBucket: 'retrouvetout-c92ba.firebasestorage.app',
    iosBundleId: 'com.example.retrouveTout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTUJNMdaDOWdlj-LDMSkS7Lm5a2fRG1EA',
    appId: '1:930156239352:web:774c013c5bbd0995861e0d',
    messagingSenderId: '930156239352',
    projectId: 'retrouvetout-c92ba',
    authDomain: 'retrouvetout-c92ba.firebaseapp.com',
    storageBucket: 'retrouvetout-c92ba.firebasestorage.app',
    measurementId: 'G-FB9ZLCV1KB',
  );
}
